### PR TITLE
Implement role lookup by name

### PR DESCRIPTION
**Pull request by tlloydthwaites**
See https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_roles_resource 'Get a role by name'

### CODE REVIEW

**Comment by looorent** [comment]
Thanks for your contribution, @tlloydthwaites !
It will be part of version `1.0.19` in a few minutes.

**Comment by tlloydthwaites** [comment]
Thanks, I noticed that the changes are misattributed in the changelog 😀

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by looorent** [comment]
Well spotted, it is updated :)

**Comment by tlloydthwaites** [comment]
Awesome, thanks! 😁

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
